### ISSUE TITLE
Home Landing Page Update

### ISSUE THREAD

**Issue by apestoptalent** [apestoptalent/Btc-Transfer-Wallet#5]
- [ ] Change Logo Icon of first page using below logo
![Screenshot_6](https://github.com/apestoptalent/Btc-Transfer-Wallet/assets/154848943/312c3064-0b59-4e50-aa14-819a7977bbc3)
![Screenshot_7](https://github.com/apestoptalent/Btc-Transfer-Wallet/assets/154848943/6648e837-d828-4838-b298-6e6deb48f993)

- [ ] Modify below content 
![Screenshot_9](https://github.com/apestoptalent/Btc-Transfer-Wallet/assets/154848943/a2938e5a-ba68-4c31-b108-46b3fb1bad28)
- "Bitcoin is characterized by its decentralized nature, setting it apart from traditional fiat currencies which are controlled and regulated by central authorities. Unlike fiat currencies, bitcoins are not issued by governmental institutions or central banks."
- "Bitcoin is utilized globally for sending money, making online purchases, and anonymous transactions due to its ease, speed, low fees, and untraceability."
- "Bitcoin transactions are protected by cryptography, which hides the identities of the sender and receiver, making them pseudonymous."

**Comment by knowledgeAlan** [comment]
Fix issue #5 73e1645d60c02704865568ad6676b7980dc868bd
