### ISSUE TITLE
Add Cryptocurrency to First Page

### ISSUE THREAD

**Issue by apestoptalent** [apestoptalent/Btc-Transfer-Wallet#6]
- [ ] add more coin to price information panel
![Screenshot_10](https://github.com/apestoptalent/Btc-Transfer-Wallet/assets/154848943/86cdd6ec-e14c-4738-8936-159b1fe09afc)

currently is shows price of
BTC, ETH, USDT, BNB, SOL, Lido, XRP,  USDC, Cardano, Dogecoin, 

need add price data of bellow coin
Shiba inu, AVAX, TRX, Dot, Link, Matic
![Screenshot_11](https://github.com/apestoptalent/Btc-Transfer-Wallet/assets/154848943/eed936e9-b019-4306-a2fd-7c0ab70b12fe)

It is using coinmarketcap API

**Comment by HeroaDev** [comment]
This is not for fixing.... Don't need to try to fix anymore
